apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis-service
    type: demo-voting-app
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-pod
    app: demo-voting-app
